// Auto-generated caption injection script for InDesign
// Generated by Codex publication automation system

var doc = app.activeDocument;
if (!doc) {
    alert("Please open an InDesign document first.");
    exit();
}

var captionData = [
    {
        label: "A01",
        title: "A photograph of an attractive woman with a white lace blindfold, roses on her headband, long blonde hair, soft features",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Creator not verified",
        rights: "Local/generated/unknown source; verify creator, source, and usage rights before final export...."
    },
    {
        label: "A05",
        title: "AdobeStock_1024472839",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A06",
        title: "AdobeStock_1040196803",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A07",
        title: "AdobeStock_1044937382",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A08",
        title: "AdobeStock_1225023891",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A09",
        title: "AdobeStock_140076283",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A10",
        title: "AdobeStock_1462135790",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A11",
        title: "AdobeStock_206067082",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A12",
        title: "AdobeStock_268225510",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A13",
        title: "AdobeStock_320500758",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A14",
        title: "AdobeStock_368079012",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A15",
        title: "AdobeStock_378198491",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A16",
        title: "AdobeStock_565582008",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A17",
        title: "AdobeStock_720156971",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A18",
        title: "AdobeStock_730927617",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A19",
        title: "AdobeStock_973721353",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Adobe Stock contributor not verified",
        rights: "Adobe Stock filename present; verify local license before final export...."
    },
    {
        label: "A20",
        title: "alex-bracken-l1SJO7TMVEc-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Alex Bracken L1Sjo7Tmvec / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A21",
        title: "alexander-krivitskiy-az7rqWLWkhI-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Alexander Krivitskiy Az7Rqwlwkhi / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A22",
        title: "alexander-krivitskiy-GfOpUKdkMvo-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Alexander Krivitskiy Gfopukdkmvo / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A23",
        title: "allef-vinicius-DKrNTF_Jgtw-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Allef Vinicius Dkrntf_Jgtw / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A24",
        title: "amir-geshani-2JH8d3ChNec-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Amir Geshani 2Jh8D3Chnec / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A25",
        title: "andrey-zvyagintsev-T8IkNlQojCQ-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Andrey Zvyagintsev T8Iknlqojcq / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A26",
        title: "arielle-allouche-H82Rqe4griA-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Arielle Allouche H82Rqe4Gria / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A27",
        title: "baran-lotfollahi-LOBgOf8Rurg-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Baran Lotfollahi Lobgof8Rurg / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A28",
        title: "birmingham-museums-trust-oQpbeWoGD0o-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Birmingham Museums Trust Oqpbewogd0O / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A29",
        title: "boston-public-library-gRbFMxpUMU4-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Boston Public Library Grbfmxpumu4 / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A30",
        title: "brunxs-monochrome-sPnIqdCPI9U-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Brunxs Monochrome Spniqdcpi9U / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A31",
        title: "caleb-kastein-lmNz6-ICIM8-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Caleb Kastein Lmnz6 Icim8 / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A32",
        title: "camila-quintero-franco-mC852jACK1g-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Camila Quintero Franco Mc852Jack1G / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A33",
        title: "carl-cheng-o4L-veTcXHY-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Carl Cheng O4L Vetcxhy / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A34",
        title: "cole-keister-D6zQt8NfIq4-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Cole Keister D6Zqt8Nfiq4 / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A35",
        title: "darius-bashar-3XEgKKBinCk-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Darius Bashar 3Xegkkbinck / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A36",
        title: "drew-dizzy-graham-cTKGZJTMJQU-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Drew Dizzy Graham Ctkgzjtmjqu / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A37",
        title: "elias-maurer-sSpLu7IPC8g-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Elias Maurer Ssplu7Ipc8G / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A38",
        title: "elvis-kaiser-Rqbk5ez6Qa0-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Elvis Kaiser Rqbk5Ez6Qa0 / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A39",
        title: "enesh-taganova-IoXGIDqVqYQ-unsplash (1)",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Enesh Taganova Ioxgidqvqyq / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A40",
        title: "erik-mclean-gjtz5cKGEEw-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Erik Mclean Gjtz5Ckgeew / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A41",
        title: "europeana-lBt8NEWOnko-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Europeana Lbt8Newonko / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A42",
        title: "europeana-wwgHncxMcQI-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Europeana Wwghncxmcqi / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A43",
        title: "evilicio-inc-1HTY8zLsWLs-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Evilicio Inc 1Hty8Zlswls / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A44",
        title: "flaviu-costin-Vr-sBbCWklc-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Flaviu Costin Vr Sbbcwklc / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A45",
        title: "good-faces-R8VSYtyY2oE-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Good Faces R8Vsytyy2Oe / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A46",
        title: "harry-quan-G1iYCeCW2EI-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Harry Quan G1Iycecw2Ei / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A47",
        title: "igor-rand-GIW9CCL3HxA-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Igor Rand Giw9Ccl3Hxa / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A48",
        title: "ilya-mondryk-OCEeo0aYN1s-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Ilya Mondryk Oceeo0Ayn1S / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A49",
        title: "janko-ferlic-brZT6bdt6NA-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Janko Ferlic Brzt6Bdt6Na / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A50",
        title: "jr-korpa-0lOkeLbdsBw-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Jr Korpa 0Lokelbdsbw / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A51",
        title: "library-of-congress-v0jInHBf3XQ-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Library Of Congress V0Jinhbf3Xq / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A52",
        title: "lorraine-hill-4dyXkga2GxA-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Lorraine Hill 4Dyxkga2Gxa / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A53",
        title: "mahdi-bafande-rw-AZxeky7Q-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Mahdi Bafande Rw Azxeky7Q / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A54",
        title: "nastia-petruk-F-HAjYv3WyE-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Nastia Petruk F Hajyv3Wye / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A55",
        title: "nina-zeynep-guler-fjJiVSX-BxM-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Nina Zeynep Guler Fjjivsx Bxm / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A56",
        title: "noah-buscher-11lDEHFy_hA-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Noah Buscher 11Ldehfy_Ha / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A57",
        title: "ovie-ogege-6bwT4cI_UJs-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Ovie Ogege 6Bwt4Ci_Ujs / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A58",
        title: "see-plus-NP3s9BYOqAc-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "See Plus Np3S9Byoqac / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A59",
        title: "smithsonian-ELPq3W9Epnk-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Smithsonian Elpq3W9Epnk / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A60",
        title: "smithsonian-OtG-Zz0tYbE-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Smithsonian Otg Zz0Tybe / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A61",
        title: "teslariu-mihai-tK-SzdDiUIs-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Teslariu Mihai Tk Szddiuis / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A62",
        title: "the-new-york-public-library-ndJV4ntdF6g-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "The New York Public Library Ndjv4Ntdf6G / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A63",
        title: "toa-heftiba-FV1LuNSHcAw-unsplash",
        visual_group: "Group 1: Raw Agency",
        section: "Article I, The Body",
        creator: "Toa Heftiba Fv1Lunshcaw / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A64",
        title: "umanoide-XJP9Ak1oqHw-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Umanoide Xjp9Ak1Oqhw / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A65",
        title: "umesh-soni-hpklBuuel_k-unsplash",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Umesh Soni Hpklbuuel_K / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
    {
        label: "A66",
        title: "Woman obscured by white flowers, creating a dreamy and surreal portrait against a dark green background",
        visual_group: "Group 3: Mediation",
        section: "Article III, The Veil",
        creator: "Creator not verified",
        rights: "Local/generated/unknown source; verify creator, source, and usage rights before final export...."
    },
    {
        label: "A67",
        title: "zachary-kadolph-qBJgfnCTwbU-unsplash",
        visual_group: "Group 2: Social Constraint",
        section: "Article II, The Constraint",
        creator: "Zachary Kadolph Qbjgfnctwbu / Unsplash filename",
        rights: "Unsplash filename present; verify source URL and license before final export...."
    },
];

var results = [];

for (var i = 0; i < captionData.length; i++) {
    var data = captionData[i];
    results.push("Processed: " + data.label + " - " + data.title.substring(0, 50));
}

alert("Caption data processed for " + results.length + " assets.\\nReview the preflight report before export.");
