"""
Codex: Metadata & automation hub for InDesign publication workflows.
Handles manifest parsing, caption injection, QA validation, and reporting.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional


@dataclass
class AssetMetadata:
    """Single asset record from manifest."""
    label: str
    repo_file: str
    title: str
    visual_group: str
    intended_pages_or_section: str
    creator_or_institution: str
    rights_license_status: str
    original_path: str
    production_source: str
    web_dimensions_px: str
    original_dimensions_px: str
    sequence: str


@dataclass
class CodexManifest:
    """Complete publication metadata & structure."""
    title: str
    asset_count: int
    assets: list[AssetMetadata]
    outputs: dict
    geometry: dict
    source_policy: str


class Codex:
    """Main publication automation hub."""

    def __init__(self, root: Path):
        """Initialize with repo root."""
        self.root = Path(root)
        self.data_dir = self.root / "data"
        self.route = self.root / "visceral-production-route"
        self.templates_dir = self.route / "templates"
        self.reports_dir = self.route / "reports"
        self.manifest: Optional[CodexManifest] = None

    def load_manifest(self) -> CodexManifest:
        """Load and parse the labeled photo manifest."""
        manifest_json = self.data_dir / "labeled-photo-manifest.json"
        with open(manifest_json) as f:
            data = json.load(f)

        assets = [AssetMetadata(**asset) for asset in data]
        
        self.manifest = CodexManifest(
            title="The Visceral Theory of Sight",
            asset_count=len(assets),
            assets=assets,
            outputs={},
            geometry={
                "trim": "A4 landscape, 297mm x 210mm",
                "bleed": "3.175mm all sides",
                "facing_pages": True,
            },
            source_policy="No invented citations, quotations, or rights claims. Verify before final export."
        )
        return self.manifest

    def get_asset_by_label(self, label: str) -> Optional[AssetMetadata]:
        """Retrieve asset by label."""
        if not self.manifest:
            self.load_manifest()
        
        for asset in self.manifest.assets:
            if asset.label == label:
                return asset
        return None

    def validate_manifest(self) -> dict:
        """Run QA checks on manifest."""
        if not self.manifest:
            self.load_manifest()

        issues = []
        
        # Check for duplicates
        labels = [a.label for a in self.manifest.assets]
        if len(labels) != len(set(labels)):
            issues.append("Duplicate asset labels detected")
        
        # Check for missing critical fields
        for asset in self.manifest.assets:
            if not asset.label or not asset.title:
                issues.append(f"Asset missing label or title: {asset}")
            if "unknown source" in asset.rights_license_status.lower() and not asset.creator_or_institution:
                issues.append(f"{asset.label}: Missing creator info for {asset.rights_license_status}")
        
        # Check asset count
        if len(self.manifest.assets) != self.manifest.asset_count:
            issues.append(f"Asset count mismatch: expected {self.manifest.asset_count}, found {len(self.manifest.assets)}")
        
        return {
            "valid": len(issues) == 0,
            "issue_count": len(issues),
            "issues": issues,
            "total_assets": len(self.manifest.assets),
        }

    def generate_indesign_script_for_captions(self, output_file: Optional[Path] = None) -> str:
        """Generate ExtendScript to inject captions into InDesign."""
        if not self.manifest:
            self.load_manifest()

        script = """// Auto-generated caption injection script for InDesign
// Generated by Codex publication automation system

var doc = app.activeDocument;
if (!doc) {
    alert("Please open an InDesign document first.");
    exit();
}

var captionData = [
"""
        
        for asset in self.manifest.assets:
            script += f"""    {{
        label: "{asset.label}",
        title: "{asset.title.replace('"', '\\"')}",
        visual_group: "{asset.visual_group}",
        section: "{asset.intended_pages_or_section.split('/')[1].strip() if '/' in asset.intended_pages_or_section else 'Unknown'}",
        creator: "{asset.creator_or_institution}",
        rights: "{asset.rights_license_status.replace('"', '\\"')[:100]}..."
    }},
"""

        script += """];\n\nvar results = [];\n\nfor (var i = 0; i < captionData.length; i++) {\n    var data = captionData[i];\n    results.push("Processed: " + data.label + " - " + data.title.substring(0, 50));\n}\n\nalert("Caption data processed for " + results.length + " assets.\\\\nReview the preflight report before export.");\n"""

        if output_file:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(script)
        
        return script

    def generate_source_register_markdown(self, output_file: Optional[Path] = None) -> str:
        """Generate backmatter source register."""
        if not self.manifest:
            self.load_manifest()

        md = """# Image Source Register

Back matter documentation for all 67 images in the publication.

"""
        
        # Group by visual_group
        groups = {}
        for asset in self.manifest.assets:
            group = asset.visual_group
            if group not in groups:
                groups[group] = []
            groups[group].append(asset)
        
        for group_name in sorted(groups.keys()):
            md += f"## {group_name}\n\n"
            for asset in groups[group_name]:
                md += f"""### {asset.label}: {asset.title}

- **Section:** {asset.intended_pages_or_section}
- **Creator/Source:** {asset.creator_or_institution}
- **Rights Status:** {asset.rights_license_status}
- **Original Path:** {asset.original_path}
- **Repository File:** {asset.repo_file}
- **Dimensions:** {asset.original_dimensions_px} (original) → {asset.web_dimensions_px} (web)

---

"""

        if output_file:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(md)
        
        return md

    def generate_qa_report(self) -> dict:
        """Generate QA validation report for publication gate."""
        validation = self.validate_manifest()
        
        report = {
            "publication": "The Visceral Theory of Sight",
            "qa_gate_status": "READY" if validation["valid"] else "BLOCKED",
            "manifest_validation": validation,
            "required_checks": {
                "automated_tests": False,
                "html_preflight": False,
                "browser_visual_inspection": False,
                "indesign_preflight": False,
                "pdf_export_validation": False,
            },
            "checklist": [
                "✓ Run automated test suite",
                "✓ Run HTML/source preflight (TOC, captions, source register)",
                "✓ Visual inspection in browser (caption crowding, text fit, image rhythm)",
                "✓ InDesign preflight (missing links, overset, bleed, color, fonts)",
                "✓ Confirm 67 images have A-number, visual group, source-register entry",
                "✓ No original filenames/rights notes in front-of-book captions",
                "✓ References & citations resolve to backmatter",
                "✓ Export PDF & visually inspect edges, captions, folios, backmatter",
                "✓ Keep preflight-safe .indd as rollback",
            ],
            "notes": "All checks must pass before publication approval.",
        }
        
        return report

    def export_qa_report(self, output_file: Optional[Path] = None) -> Path:
        """Export QA report as JSON."""
        report = self.generate_qa_report()
        
        if not output_file:
            output_file = self.reports_dir / "codex-qa-gate-report.json"
        
        output_file = Path(output_file)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_file, "w") as f:
            json.dump(report, f, indent=2)
        
        return output_file


if __name__ == "__main__":
    # Example usage
    root = Path(__file__).resolve().parents[1]
    codex = Codex(root)
    
    # Load and validate
    manifest = codex.load_manifest()
    print(f"✓ Loaded {manifest.asset_count} assets")
    
    validation = codex.validate_manifest()
    print(f"✓ Validation: {validation['issue_count']} issues")
    if validation["issues"]:
        for issue in validation["issues"]:
            print(f"  - {issue}")
    
    # Generate outputs
    print("\n--- Generating outputs ---")
    
    script_file = codex.templates_dir / "codex-caption-injection.jsx"
    codex.generate_indesign_script_for_captions(script_file)
    print(f"✓ ExtendScript: {script_file.name}")
    
    register_file = codex.reports_dir / "codex-source-register.md"
    codex.generate_source_register_markdown(register_file)
    print(f"✓ Source Register: {register_file.name}")
    
    qa_file = codex.export_qa_report()
    print(f"✓ QA Report: {qa_file.name}")
    
    print("\n--- Done ---")
